### ISSUE TITLE
build script

### ISSUE THREAD

**Issue by klaemo** [sto3psl/typoCSS#1]
Moin,
in der `package.json` hast du die Zeile:

`"build": "gulp clean & gulp css & gulp build-js"`

Die führt die drei Befehle parallel (gleichzeitig) aus. Ich denke, du willst aber bestimmt `clean` vor den beiden anderen ausführen:
`"build": "gulp clean && (gulp css & gulp build-js)"`
Das sollte es tun. :)

`&&`: nacheinander ausführen in bash
`&`: parallel ausführen in bash

**Comment by sto3psl** [comment]
Ist gefixed. Danke :smile:
